### ISSUE TITLE
DAX prompt is not working

### ISSUE THREAD

**Issue by gbourant** [pipelight/pipelight#13]
Since the project has DAX support it would be nice if we could use the prompts like `$.prompt`.
Currently when i use something like

```javascript
const name = await $.prompt({
  message: "What's your name?",
  default: "Dax", // prefilled value
  noClear: true, // don't clear the text on result
});
```

It throws the following error

```
error:   × error: Uncaught (in promise) Error: Cannot prompt when not a tty. (Prompt: 'What's your name?')
  │     throw new Error(`Cannot prompt when not a tty. (Prompt: '${options.message}')`);
  │           ^
  │     at createSelection (https://deno.land/x/dax@0.39.2/src/console/utils.ts:109:11)
  │     at maybePrompt (https://deno.land/x/dax@0.39.2/src/console/prompt.ts:50:10)
  │     at Function.prompt (https://deno.land/x/dax@0.39.2/src/console/prompt.ts:39:10)
  │     at eventLoopTick (ext:core/01_core.js:168:7)
```

**Comment by pipelight** [comment]
I am inspecting this...
